### ISSUE TITLE
C++ Data race UB on the non-atomic `vector<T>`, possible tearing with wider T

### ISSUE THREAD

**Issue by pcordes** [bittnkr/uniq#2]
As discussed on https://stackoverflow.com/questions/25709548/lock-free-multiple-producer-consumer-queue-in-c11/59622729?noredirect=1#comment105424967_59622729 and 
https://chat.stackoverflow.com/rooms/205556/discussion-between-bittnkr-and-peter-cordes

Consider this sequence of events:

* A writer calls `push`.  It sleeps or stalls after `head.compare_exchange_weak(t, t + 1)` succeeds, making `head=1` globally visible, but before `buffer[0] = item` happens.

* Another thread running `pop` can then see `tail != head` and **can read `buffer[0]` at the same time another thread is writing it.**

The safety of your code depends on read/write of buffer elements being atomic, but your in your code it's a `vector<T>` not `vector<atomic<T>>` (which you could use instead with `memory_order_relaxed`).  You could see tearing *in practice* with `int64_t` on a 32-bit machine, e.g. compile with `gcc -O3 -m32` on x86.  (And of course it's obviously ISO C++ UB.)

Or with `T = unsigned __int128` on a 64-bit machine. Or with `T` being a class type with overloaded `operator=` and `operator bool`.

It's also clearly C++ UB for `pop` to spin-wait on the non-atomic element value becoming non-zero.

`!buffer[t & mask]` could in theory be hoisted out of the loop when it's the same index every time, but in practice compilers will just reload it because `t` can change inside the loop.

BTW, you should probably hoist the `t = tail` out of the loop and just use the value from the CAS-fail load (`tail.compare_exchange_weak(t, t+1);`  updates `t` on failure).  Or move it to inside the spin-wait for non-empty loop.

```
// why was this virtual?  I don't see why you'd want that overhead
T pop() {
    T r;
    unsigned tmask, t = tail;   // unsigned so t+1 avoids signed-overflow UB
    do {
        while (t == head) {
            sched_yield(); // if empty, wait for item
            t = tail;    // no point leaving the loop if tail moved, too
        }
       tmask = t & mask;
        r = buffer[tmask];   // or buffer[tmask].load(std::memory_order_relaxed);
    }  while (!r ||
           !tail.compare_exchange_weak(t, t + 1) // tail = t+1 (ons swsr)
        );
    // no need to reload buffer[tmask]
    // and we can only leave the loop if CAS didn't modify t
    buffer[tmask] = 0;     // FIXME: this can race with a writer in an almost-full queue
    return r;
}
```

This doesn't fix any of the bugs, but makes it more efficient in preparation for replacing `buffer` with a vector or array of `atomic<T>`

**Comment by pcordes** [comment]
Since you asked nicely, I created a testcase that demonstrates tearing caused by the non-atomicity of your non-atomic vectors.  https://gist.github.com/pcordes/edcaf9089b02e787c6878e880c1f135a
I reduced it down to `pairs = 1, Items = 1000*1000;` and still get tearing for queue type = `uint64_t`, when compiled with `g++ -m32 -O1` (a 32-bit machine loads/stores `uint64_t` as two separate 32-bit halves, unless you use `atomic<>` to get it to use SSE `movq`)

I had to make the producer push values that had a non-zero upper half; pushing `1` every time is a very poor test for detecting data races!

The checksum is too high by a multiple of 0x20 (32, the queue size), even for 1 producer 1 consumer with only 1M reps.  Sometimes that multiple is zero, more often not.  (Tested on i7-6700k, gcc9.1, Arch Linux)

Several runs to illustrate:

```
peter@volta:/usr/local/src/uniq/sandbox$ g++ -fno-pie -no-pie hello.cpp -pthread -Wall -O1 -m32 -o test && ./test
Produced:   1000000, sum = 0x7a1946a5a2920
Consumed:   1000000, sum = 0x7a1946a5a2920

Checksum: 0 (it must be zero)
peter@volta:/usr/local/src/uniq/sandbox$ ./test
Produced:   1000000, sum = 0x7a1946a5a2920
Consumed:   1000000, sum = 0x7a1946a5a2820

Checksum: 0x100 (it must be zero)
peter@volta:/usr/local/src/uniq/sandbox$ ./test
Consumed:   1000000, sum = 0x7a1946a5a2840
Produced:   1000000, sum = 0x7a1946a5a2920

Checksum: 0xe0 (it must be zero)
peter@volta:/usr/local/src/uniq/sandbox$ ./test
Produced:   1000000, sum = 0x7a1946a5a2920
Consumed:   1000000, sum = 0x7a1946a5a2840

Checksum: 0xe0 (it must be zero)
peter@volta:/usr/local/src/uniq/sandbox$ ./test
Consumed:   1000000, sum = 0x7a1946a5a2820
Produced:   1000000, sum = 0x7a1946a5a2920

Checksum: 0x100 (it must be zero)
```

**Comment by pcordes** [comment]
I had earlier raised concerns about `buffer[t] = 0;` in pop from racing with `buffer[t] = item;` in push, leaving you with an element that the writer thinks it wrote but which actually still holds a `0` value.  If that happened, then when the reader wraps around to it, it would get stuck and spin forever waiting for a write that already happened (but got stepped on).

I think that's actually fine, if `buffer<T>` were `buffer<atomic<T>>`.  I had earlier not noticed that push also spins on seeing `buffer[t & mask] != 0` before writing it.  When I first looked at the code, I assumed all the slot-claiming was done via head/tail specifically *because* the buffer itself is of non-atomic objects, so it wouldn't be safe for multiple threads to read/write them.  No comments in the code pointed out what was going on.

This *happens* to work when `T` is small enough to be "naturally" atomic in asm.  Compilers also treat `head.compare_exchange_weak(t, t + 1)` as a memory barrier, stopping them from moving around the load or hoisting it out of the loop.  (Or else we get that effect because of the possibility of `t` changing in the loop).  It's totally UB in C++, but it happens to compile to working asm.

Anyway, instead of a separate `isfree` array, making a struct of `{T data; atomic<bool> inuse;}` would give more locality, but OTOH waste more space for int64_t.  That would avoid needing a sentinel value that queue users have to avoid, though.

**Comment by bittnkr** [comment]
Dear Peter,
Thank you for your code review.  You are right, there was a bug on the implementation using 64 bit Integers (but the solution its still valid). 

I rewrote the uniq.h and hello.cpp to accommodate your example, and now it's working perfectly.
This is is output I got running the corrected version:

```
Creating 4 producers & 4 consumers
to flow 10.000.000 items trough the queue.

Produced: 10.743.668.245.000.000
Consumed: 5.554.289.678.184.004
Produced: 10.743.668.245.000.000
Consumed: 15.217.833.969.059.643
Produced: 10.743.668.245.000.000
Consumed: 7.380.542.769.600.801
Produced: 10.743.668.245.000.000
Consumed: 14.822.006.563.155.552
**Checksum: 0 (it must be zero)**
```

Can you verify it now?

**Comment by bittnkr** [comment]
Please check the new [hello.cpp](https://github.com/bittnkr/uniq/blob/master/sandbox/hello.cpp)

**Comment by pcordes** [comment]
> Dear Peter,
> Thank you for your code review. You are right, there was a bug on the implementation using 64 bit Integers (but the solution its still valid).
>
> I rewrote the uniq.h and hello.cpp to accommodate your example, and now it's working perfectly.


It would be valid if you implemented it safely, using `atomic<bool> isFree` elements.  (Preferably make `buffer[]` a vector of structs including an atomic member; fewer buckets per cache line means less false sharing between threads.)

But instead you just changed it so it happens to work once again, without doing anything to avoid the data-race UB I pointed out.

Plus you introduced more stuff that could go wrong in practice:

```
    buffer[i & mask] = item;
    isFree[i & mask] = 0;
```

are both non-atomic so it's UB and ISO C++ doesn't guarantee anything about the unsynchronized reader.  In practice presumably this and the corresponding loads will compile to actual asm stores and loads, but since it's non-atomic you won't get any memory barriers or ordering.

If it happens to compile into asm that matches the source order then it will be safe on x86 (where all stores are release stores, and all loads are release loads).

But on weakly-ordered ISAs like ARM / AArch64, **runtime StoreStore reordering is now a real problem.** Your code depends on `isFree[i & mask] = 0;` being a release store, letting other threads know that the data in `buffer` is valid.  See https://preshing.com/20120930/weak-vs-strong-memory-models/

It also depends on `pop` being an acquire load of `isFree[o & mask]`, although for most ISAs in practice having the loads from isFree and buffer separated by a seq_cst atomic RMW (`compare_exchange_weak`) will typically introduce enough barriers.  Not sure about AArch64.

Just make `isFree` a vector of `atomic<bool>` (or better make `buffer` an array of structs) and use it with `memory_order_release` and `acquire`, which are free on x86.  IIRC that's doable even though atomic<T> is not trivially copyable since you're never growing or shrinking the vector.

It's pointless to write code that abuses non-atomic variables in ways that happen to work; you can get the same asm for x86 safely with atomics, or the necessary asm for other platforms.

Also, you could check if [`atomic<T>::is_always_lock_free`](https://en.cppreference.com/w/cpp/atomic/atomic/is_always_lock_free) in your template and if so just use `atomic<T>` in your buffer, with a sentinel value like you were before.  Then I think you just need mo_relaxed loads/stores.  (IDK why you have `virtual` functions, seems like pointless overhead.)

**Comment by bittnkr** [comment]
Thanks for the profound observations. 

But despite I didn't test the algorithm on ARM, I think that this do no apply because of the very nature of the solution, the memory access is protected by the two atomic variables (in & out), which guarantee the impossibility of data races. 

If a thread successfully update the register, the space/seat was acquired definitively. 

Please try to break it again. Stress the solution, increasing the threads, the number or nature of items flowing or reducing the buffer. If you can obtain a checksum different than zero, I will can agree with you. 

BTW: You are right about the virtual functions. I removed them. 

Thanks again.
