### ISSUE TITLE
Consider using an MIT license

### ISSUE THREAD

**Issue by slnovak** [bittnkr/uniq#3]
Hello,

This is a cool library!

I'd be interested in using + contributing to this library, however the GPL is rather restrictive, especially for folks who would be interested in using this library for work projects.

Would you please consider moving to an MIT license?

Thanks!

**Comment by bittnkr** [comment]
Hello buddy,
You are right. I understand that restriction. 

It was released under GNU to protect it from the big players. I really don't want to see Google, Microsoft, Apple or Intel taking this and closing it in between their walls (or in silicon) and making whatever they want without giving anything back to the open source community. If they want to use this, I want at least be notified.

Given the nature of the finding. I see a whole new operational system coming out of it. (Hence the name, uniQ means a single queue OS). In the same way Linux is released under GNU, so uniQ. 

I can give a dual, lifetime licence for anyone who want to use this by agreement. If you want to use it in a closed source project, its a matter of asking and saying the boundaries of your project. 

I can give you the permission at a very low cost, or even no cost if you are coding in a least restrictive licences as MIT or BSD.

Collaboration is very welcome, I'm just asking you release your derived work. 

What do you think?

**Comment by slnovak** [comment]
Cool, thanks!

I'll be looking into making an implementation on top of Javascript's SharedArrayBuffer (+ atomics) to be able to push data to Web Workers. It'll be interesting to see the performance improvement over the convention `postMessage` interface.

Thanks for sharing this cool algorithm!

**Comment by bittnkr** [comment]
I'm glad you understand.
I started something in this direction too. 
For now, I think its too crude to be published, but if you want I can share it with you.

**Comment by yrashk** [comment]
> Cool, thanks!
> 
> I'll be looking into making an implementation on top of Javascript's SharedArrayBuffer (+ atomics) to be able to push data to Web Workers. It'll be interesting to see the performance improvement over the convention `postMessage` interface.
> 
> Thanks for sharing this cool algorithm!

Learned about UniQ when I posted about my work on a SharedArrayBuffer + Atomics queue for browsers. https://news.ycombinator.com/item?id=22655643

I do indeed see a good, 3-4x speed comparing to `postMessage` up so far (but my queue is a bit buggy, so I am not releasing it just yet). My rough design inspiration is Bipartite Buffer https://www.codeproject.com/articles/3479/the-bip-buffer-the-circular-buffer-with-a-twist

Just as I am trying to create a working model of my queue in TLA+, I am also writing down Uniq implementation in TLA+ to prove or disprove it.

**Comment by bittnkr** [comment]
Today commited a implementation of the algorithm in Javascript using Worker Threads and SharedArrayBuffer. 

For now, just flowing integers, but its working fairly well. (3.5 secs to flow 10M items vs 2.5 of the c++ version)

Take a look on the js folder of the project.

to run the test, just type inside the uniq main folder:
`time /usr/bin/node  js/test.js`

**Comment by slnovak** [comment]
Nice job, @bittnkr!

A few thoughts:

- I'm interested in using the JS library to communicate between the main thread in the browser and WebWorkers without having to go through postMessage. I'm working on a benchmark to compare the two.

- I'm also interested in using a `Float32Array` for passing data back and forth. As I understand, Uniq uses the value `0` to denote an empty space in the queue. What changes would be needed to replace that value with `NaN` since that value can be store in a `Float32Array` instance?

- Lastly, back to the discussion on licensing, using GPL components in Javascript code is somewhat confusing. Do you think an LGPL license would be practical, which allows for non-derivative uses of the source code to be distributed under other licenses? Any derivative work would still be covered under the LGPL which would still protect the code and ensure that those changes are contributed back to the company.

Thanks and keep up the awesome work!

**Comment by slnovak** [comment]
I ran some initial benchmarks of sending 1M events via postMessage vs. uniq in the browser:

On a 2017 Macbook Air and Chrome 80.0.3987.149:

|  Test Case (buffer size)  | Time to send 1M | Time to receive 1M |
| ----------- | --------------- | ------------------ |
| postMessage |      11.714 sec |         13.460 sec |
|   uniq (64) |      11.065 sec |         18.745 sec |
|  uniq (512) |      10.059 sec |         12.903 sec |
| uniq (1024) |       9.999 sec |         12.871 sec |

Feel free to take a look at the code for these benchmarks and let me know if you have any suggestions to change the testing approach.

https://github.com/slnovak/uniq-benchmark

Cheers!

**Comment by bittnkr** [comment]
> Nice job, @bittnkr!
> 
> A few thoughts:
> 
> * I'm interested in using the JS library to communicate between the main thread in the browser and WebWorkers without having to go through postMessage. I'm working on a benchmark to compare the two.
> * I'm also interested in using a `Float32Array` for passing data back and forth. As I understand, Uniq uses the value `0` to denote an empty space in the queue. What changes would be needed to replace that value with `NaN` since that value can be store in a `Float32Array` instance?
> * Lastly, back to the discussion on licensing, using GPL components in Javascript code is somewhat confusing. Do you think an LGPL license would be practical, which allows for non-derivative uses of the source code to be distributed under other licenses? Any derivative work would still be covered under the LGPL which would still protect the code and ensure that those changes are contributed back to the company.
> 
> Thanks and keep up the awesome work!

I think you are right, since is a library it makes more sense to release it on LGPL I'll change it soon.
